[tool.poetry]
name = "maze-solver"
version = "0.1.0"
description = ""
authors = ["Jakub F. Bortlík <jakub.bortlik@proton.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
